name: fair
description: Flutter Fair is a package used to update widget tree dynamically.
version: 0.3.1
homepage: https://fair.58.com/

environment:
  sdk: ^2.13.4
  flutter: ^2.2.3

dependencies:
  flutter:
    sdk: flutter
  fair_annotation:
    git:
      url: https://github.com/shishaopo/fair.git
      path: fair_annotation
  fair_version:
    git:
      url: https://github.com/shishaopo/fair.git
      path: fair_version/flutter_2_2_3
  flat_buffers: ^1.12.0
  url_launcher: ^6.0.9
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^0.38.5
  pedantic: ^1.9.2
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
