name: doc_server
description: A web server built using the shelf package.
environment:
  sdk: ^2.13.4
  flutter: ^2.2.3

dependencies:
  args: ^2.1.1
  shelf: ^1.1.4
  shelf_static: ^1.0.0
  shelf_router: ^1.0.0
  io: ^1.0.2

dev_dependencies:
  pedantic: ^1.8.0
