name: fair_annotation
description: Annotation package for Flutter Fair, work with fair compiler.
version: 0.2.1
homepage: https://fair.58.com/

environment:
  sdk: ^2.13.4
  flutter: ^2.2.3

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
